/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#101415',
        'surface-dim': '#0b0f10',
        'surface-container-low': '#181c1d',
        'surface-container': '#1c2021',
        'surface-container-high': '#272b2c',
        'surface-container-highest': '#313536',
        'surface-bright': '#363a3b',
        primary: '#4edea3',
        'primary-container': '#10b981',
        'on-surface': '#e0e3e5',
        'on-surface-variant': '#bbcabf',
        'on-primary': '#003824',
        'on-primary-container': '#00422b',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        error: '#ffb4ab',
        'error-container': '#7f1d1d',
        secondary: '#bec6e0',
        'secondary-container': '#3e465c',
      },
      fontSize: {
        'display-xl': ['72px', { fontWeight: '800', lineHeight: '1.1', letterSpacing: '-0.04em' }],
        'display-xl-mobile': ['48px', { fontWeight: '800', lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'display-lg': ['64px', { fontWeight: '700', lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'headline-lg': ['32px', { fontWeight: '700', lineHeight: '1.3' }],
        'headline-md': ['24px', { fontWeight: '600', lineHeight: '1.4' }],
        'headline-sm': ['18px', { fontWeight: '600', lineHeight: '1.4' }],
        'body-lg': ['18px', { fontWeight: '400', lineHeight: '1.6' }],
        'body-md': ['16px', { fontWeight: '400', lineHeight: '1.6' }],
        'label-md': ['14px', { fontWeight: '500', lineHeight: '1.2', letterSpacing: '0.02em' }],
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '24px',
        'section-gap': '120px',
        'container-max': '1280px',
      },
      borderRadius: {
        'DEFAULT': '4px',
        'md': '8px',
        'lg': '16px',
        'xl': '24px',
      },
    },
  },
  plugins: [],
}
