/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // New palette tokens
        background: '#FAFAFF',
        surface: '#FFFFFF',
        accent: '#0891B2',
        muted: '#64748B',
        ink: '#1E293B',
        border: '#CAD3C9',
        // Legacy aliases for backward compatibility with existing pages
        primary: '#0891B2',
        'primary-container': '#0E7490',
        on-accent: '#FFFFFF',
        on-accent-container: '#FFFFFF',
        'on-surface': '#1E293B',
        'on-surface-variant': '#64748B',
        outline: '#CAD3C9',
        'outline-variant': '#CAD3C9',
        error: '#DC2626',
        'error-container': '#FEE2E2',
        secondary: '#94A3B8',
        'secondary-container': '#3A3E4D',
        surface: '#FFFFFF',
        'surface-dim': '#F5F6FA',
        'surface-container-low': '#F5F6FA',
        'surface-container': '#FFFFFF',
        'surface-container-high': '#EAEBF1',
        'surface-container-highest': '#252733',
        'surface-bright': '#252733',
        // Dark mode colors
        'dark-bg': '#0F0F18',
        'dark-surface': '#1B1E28',
        'dark-border': '#3A3E4D',
      },
      fontSize: {
        'display-xl': ['72px', { fontWeight: '800', lineHeight: '1.1', letterSpacing: '-0.04em' }],
        'display-xl-mobile': ['48px', { fontWeight: '800', lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'display-lg': ['64px', { fontWeight: '700', lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'headline-lg': ['32px', { fontWeight: '700', lineHeight: '1.3' }],
        'headline-md': ['24px', { fontWeight: '600', lineHeight: '1.4' }],
        'headline-sm': ['18px', { fontWeight: '600', lineHeight: '1.4' }],
        'body-lg': ['18px', { fontWeight: '400', lineHeight: '1.5' }],
        'body-md': ['16px', { fontWeight: '400', lineHeight: '1.5' }],
        'label-md': ['14px', { fontWeight: '500', lineHeight: '1.4', letterSpacing: '0.02em' }],
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '24px',
        'section-gap': '96px',
        'container-max': '1280px',
      },
      borderRadius: {
        'DEFAULT': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
      },
    },
  },
  plugins: [],
}